### PR TITLE
Addition of main quests only guides

### PR DESCRIPTION
**Pull request by Krandor1**
Addition of guides without side quests called Main Quest Only Guides which are modified versions of original guides with all side quests removed.    Is my just main quest/region quest/main guild/fighters guild type quests.

### CODE REVIEW

**Comment by Krandor1** [comment]
No real need to rebase this.  Only existing file mod is ZGESO.txt to add new guide to list (which also will need another mod to update version number).   Everything else is brand new guides in a brand new file.

**Comment by Sharlikran** [comment]
Rebase this but please use an interactive rebase. I usually don't have so many `Merge branch 'Development' of https` commits.

**Comment by Krandor1** [comment]
No problem.  Will work on that tonight

**Comment by Krandor1** [comment]
Rebased.    I'm a network engineer and am starting to learn stuff like APIs and github since the industry is moving that what but stil learning things like git so you'll have to bear with me a bit.  So I did a rebase on it and I think it should be good.  Let me know if I need to do anything else.  

BTW, my fork on github  still shows "This branch is 61 commits ahead, 2 commits behind Hydra9268:master." how can I change that to point to your fork?

**Comment by Sharlikran** [comment]
Done now, if you would just install that version manually and see if you get errors for me please.

**Comment by Krandor1** [comment]
Without running through every guide with a new character to verify all guide steps I see no functional errors with this version.

**Comment by Sharlikran** [comment]
Thanks. Sorry I wasn't more clear. You would not have had to use a bunch of new characters to test things

**Pull request merged**
